-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-01-07 14:57:42 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE address 
    (
     address_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     id_address INTEGER NOT NULL , 
     country_id_country TINYINT NOT NULL , 
     breeder_id_breeder INTEGER NOT NULL , 
     city VARCHAR (64) NOT NULL , 
     postal_code VARCHAR NOT NULL , 
     street VARCHAR (128) , 
     building_number VARCHAR (16) NOT NULL , 
     apartment_number VARCHAR 
    )
GO

ALTER TABLE address ADD CONSTRAINT address_PK PRIMARY KEY CLUSTERED (address_ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE animal 
    (
     id_animal BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     id_type NUMERIC (28) NOT NULL , 
     husbandry_id_husbandry INTEGER NOT NULL , 
     birth_date DATE NOT NULL , 
     death_date DATE , 
     breed_id_breed SMALLINT NOT NULL , 
     animal_id_animal2 BIGINT NOT NULL , 
     animal_id_animal BIGINT , 
     animal_number VARCHAR (24) NOT NULL 
    )
GO

ALTER TABLE animal ADD CONSTRAINT animal_PK PRIMARY KEY CLUSTERED (id_animal)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE animal ADD CONSTRAINT animal_animal_number_UN UNIQUE NONCLUSTERED (animal_number)
GO

CREATE TABLE animal_type 
    (
     id_animal_type TINYINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     name VARCHAR (32) NOT NULL 
    )
GO

ALTER TABLE animal_type ADD CONSTRAINT animal_type_PK PRIMARY KEY CLUSTERED (id_animal_type)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE animal_type ADD CONSTRAINT animal_type_name_UN UNIQUE NONCLUSTERED (name)
GO

CREATE TABLE breed 
    (
     id_breed SMALLINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     name VARCHAR (64) NOT NULL , 
     Type_id TINYINT NOT NULL , 
     id_animal_type TINYINT NOT NULL 
    )
GO

ALTER TABLE breed ADD CONSTRAINT breed_PK PRIMARY KEY CLUSTERED (id_breed)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE breed ADD CONSTRAINT breed_name_UN UNIQUE NONCLUSTERED (name)
GO

CREATE TABLE breeder 
    (
     id_breeder INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     name VARCHAR (32) NOT NULL , 
     last_name VARCHAR (64) NOT NULL , 
     pesel CHAR (11) NOT NULL , 
     telephone_number VARCHAR (16) NOT NULL 
    )
GO

ALTER TABLE breeder ADD CONSTRAINT Breeder_PK PRIMARY KEY CLUSTERED (id_breeder)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE breeder ADD CONSTRAINT breeder_pesel_UN UNIQUE NONCLUSTERED (pesel)
GO
ALTER TABLE breeder ADD CONSTRAINT breeder_telephone_number_UN UNIQUE NONCLUSTERED (telephone_number)
GO

CREATE TABLE country 
    (
     id_country TINYINT NOT NULL , 
     country_code CHAR (2) NOT NULL , 
     name VARCHAR (32) NOT NULL 
    )
GO

ALTER TABLE country ADD CONSTRAINT country_PK PRIMARY KEY CLUSTERED (id_country)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE country ADD CONSTRAINT country_country_code_UN UNIQUE NONCLUSTERED (country_code)
GO
ALTER TABLE country ADD CONSTRAINT country_name_UN UNIQUE NONCLUSTERED (name)
GO

CREATE TABLE event 
    (
     id_event BIGINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     event_type_id_event_type SMALLINT NOT NULL , 
     description TEXT , 
     date DATE NOT NULL , 
     animal_id_animal BIGINT NOT NULL , 
     created_at DATETIME NOT NULL 
    )
GO

ALTER TABLE event ADD CONSTRAINT event_PK PRIMARY KEY CLUSTERED (id_event)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE event_type 
    (
     id_event_type SMALLINT NOT NULL IDENTITY NOT FOR REPLICATION , 
     name VARCHAR (255) NOT NULL , 
     description TEXT 
    )
GO

ALTER TABLE event_type ADD CONSTRAINT event_type_PK PRIMARY KEY CLUSTERED (id_event_type)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE event_type ADD CONSTRAINT event_type_name_UN UNIQUE NONCLUSTERED (name)
GO

CREATE TABLE feed 
    (
     id_feed INTEGER NOT NULL , 
     name VARCHAR (128) NOT NULL , 
     measure_unit_id_measure_unit TINYINT NOT NULL 
    )
GO

ALTER TABLE feed ADD CONSTRAINT feed_PK PRIMARY KEY CLUSTERED (id_feed)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE feed ADD CONSTRAINT feed_name_UN UNIQUE NONCLUSTERED (name)
GO

CREATE TABLE husbandry 
    (
     id_husbandry INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     id_breeder INTEGER NOT NULL , 
     husbandry_manager_id_husbandry_manager INTEGER , 
     husbandry_number VARCHAR (32) NOT NULL , 
     number_of_animals INTEGER NOT NULL , 
     created_at DATE NOT NULL , 
     husbandry_type_id_husbandry_type TINYINT NOT NULL , 
     breederv1_id_breeder INTEGER NOT NULL , 
     address_address_ID NUMERIC (28) NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    husbandry__IDX ON husbandry 
    ( 
     address_address_ID 
    ) 
GO

ALTER TABLE husbandry ADD CONSTRAINT Husbandry_PK PRIMARY KEY CLUSTERED (id_husbandry)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE husbandry ADD CONSTRAINT husbandry_husbandry_number_UN UNIQUE NONCLUSTERED (husbandry_number)
GO

CREATE TABLE husbandry_manager 
    (
     id_husbandry_manager INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     name VARCHAR (32) NOT NULL , 
     last_name VARCHAR (64) NOT NULL , 
     pesel CHAR (11) NOT NULL , 
     email VARCHAR (128) NOT NULL , 
     telephone_number VARCHAR (16) NOT NULL , 
     husbandry_id_husbandry INTEGER NOT NULL , 
     address_address_ID NUMERIC (28) NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    husbandry_manager__IDX ON husbandry_manager 
    ( 
     address_address_ID 
    ) 
GO

ALTER TABLE husbandry_manager ADD CONSTRAINT husbandry_manager_PK PRIMARY KEY CLUSTERED (id_husbandry_manager)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE husbandry_manager ADD CONSTRAINT husbandry_manager_pesel_UN UNIQUE NONCLUSTERED (pesel)
GO
ALTER TABLE husbandry_manager ADD CONSTRAINT husbandry_manager_email_UN UNIQUE NONCLUSTERED (email)
GO
ALTER TABLE husbandry_manager ADD CONSTRAINT husbandry_manager_telephone_number_UN UNIQUE NONCLUSTERED (telephone_number)
GO

CREATE TABLE husbandry_type 
    (
     id_husbandry_type TINYINT NOT NULL , 
     name VARCHAR (64) NOT NULL 
    )
GO

ALTER TABLE husbandry_type ADD CONSTRAINT husbandry_type_PK PRIMARY KEY CLUSTERED (id_husbandry_type)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE measure_unit 
    (
     id_measure_unit TINYINT NOT NULL , 
     name VARCHAR (64) NOT NULL , 
     unit VARCHAR (16) NOT NULL 
    )
GO

ALTER TABLE measure_unit ADD CONSTRAINT measure_unit_PK PRIMARY KEY CLUSTERED (id_measure_unit)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE nutrition 
    (
     id_nutrition BIGINT NOT NULL , 
     date DATETIME NOT NULL , 
     amount FLOAT (2) NOT NULL , 
     animal_id_animal BIGINT NOT NULL , 
     feed_id_feed INTEGER NOT NULL , 
     description TEXT 
    )
GO

ALTER TABLE nutrition ADD CONSTRAINT nutrition_PK PRIMARY KEY CLUSTERED (id_nutrition)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE product 
    (
     id_product SMALLINT NOT NULL , 
     name VARCHAR (128) NOT NULL , 
     measure_unit_id_measure_unit TINYINT NOT NULL 
    )
GO

ALTER TABLE product ADD CONSTRAINT product_PK PRIMARY KEY CLUSTERED (id_product)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE productivity 
    (
     id_productivity BIGINT NOT NULL , 
     date DATE NOT NULL , 
     product_id_product SMALLINT NOT NULL , 
     animal_id_animal BIGINT NOT NULL 
    )
GO

ALTER TABLE productivity ADD CONSTRAINT productivity_PK PRIMARY KEY CLUSTERED (id_productivity)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE system_admin 
    (
     id_system_admin SMALLINT NOT NULL , 
     name VARCHAR (32) NOT NULL , 
     last_name VARCHAR (32) NOT NULL , 
     pesel CHAR (11) NOT NULL , 
     email VARCHAR (64) NOT NULL , 
     telephone_number VARCHAR (16) NOT NULL , 
     address_address_ID NUMERIC (28) NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    system_admin__IDX ON system_admin 
    ( 
     address_address_ID 
    ) 
GO

ALTER TABLE system_admin ADD CONSTRAINT system_admin_PK PRIMARY KEY CLUSTERED (id_system_admin)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE system_admin ADD CONSTRAINT system_admin_pesel_UN UNIQUE NONCLUSTERED (pesel)
GO
ALTER TABLE system_admin ADD CONSTRAINT system_admin_email_UN UNIQUE NONCLUSTERED (email)
GO
ALTER TABLE system_admin ADD CONSTRAINT system_admin_telephone_number_UN UNIQUE NONCLUSTERED (telephone_number)
GO

CREATE TABLE vet 
    (
     id_vet INTEGER NOT NULL , 
     name VARCHAR (64) NOT NULL , 
     last_name VARCHAR (64) NOT NULL , 
     vet_licence VARCHAR (32) NOT NULL , 
     pesel CHAR (11) NOT NULL , 
     email VARCHAR (64) NOT NULL , 
     telephone_number VARCHAR (16) NOT NULL , 
     address_address_ID NUMERIC (28) NOT NULL 
    )
GO 

    


CREATE UNIQUE NONCLUSTERED INDEX 
    vet__IDX ON vet 
    ( 
     address_address_ID 
    ) 
GO

ALTER TABLE vet ADD CONSTRAINT vet_PK PRIMARY KEY CLUSTERED (id_vet)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE vet ADD CONSTRAINT vet_vet_licence_UN UNIQUE NONCLUSTERED (vet_licence)
GO
ALTER TABLE vet ADD CONSTRAINT vet_pesel_UN UNIQUE NONCLUSTERED (pesel)
GO
ALTER TABLE vet ADD CONSTRAINT vet_email_UN UNIQUE NONCLUSTERED (email)
GO

CREATE TABLE vet_treatment 
    (
     id_vet_treatment BIGINT NOT NULL , 
     name VARCHAR (64) NOT NULL , 
     description TEXT , 
     date DATE NOT NULL , 
     animal_id_animal BIGINT NOT NULL , 
     vet_id_vet INTEGER NOT NULL 
    )
GO

ALTER TABLE vet_treatment ADD CONSTRAINT vet_treatment_PK PRIMARY KEY CLUSTERED (id_vet_treatment)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE address 
    ADD CONSTRAINT address_breeder_FK FOREIGN KEY 
    ( 
     breeder_id_breeder
    ) 
    REFERENCES breeder 
    ( 
     id_breeder 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE address 
    ADD CONSTRAINT address_country_FK FOREIGN KEY 
    ( 
     country_id_country
    ) 
    REFERENCES country 
    ( 
     id_country 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE animal 
    ADD CONSTRAINT animal_animal_FK FOREIGN KEY 
    ( 
     animal_id_animal
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE animal 
    ADD CONSTRAINT animal_animal_FKv2 FOREIGN KEY 
    ( 
     animal_id_animal2
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE animal 
    ADD CONSTRAINT animal_breed_FK FOREIGN KEY 
    ( 
     breed_id_breed
    ) 
    REFERENCES breed 
    ( 
     id_breed 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE animal 
    ADD CONSTRAINT animal_husbandry_FK FOREIGN KEY 
    ( 
     husbandry_id_husbandry
    ) 
    REFERENCES husbandry 
    ( 
     id_husbandry 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE breed 
    ADD CONSTRAINT breed_animal_type_FK FOREIGN KEY 
    ( 
     Type_id
    ) 
    REFERENCES animal_type 
    ( 
     id_animal_type 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE event 
    ADD CONSTRAINT event_animal_FK FOREIGN KEY 
    ( 
     animal_id_animal
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE event 
    ADD CONSTRAINT event_event_type_FK FOREIGN KEY 
    ( 
     event_type_id_event_type
    ) 
    REFERENCES event_type 
    ( 
     id_event_type 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE feed 
    ADD CONSTRAINT feed_measure_unit_FK FOREIGN KEY 
    ( 
     measure_unit_id_measure_unit
    ) 
    REFERENCES measure_unit 
    ( 
     id_measure_unit 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry 
    ADD CONSTRAINT husbandry_address_FK FOREIGN KEY 
    ( 
     address_address_ID
    ) 
    REFERENCES address 
    ( 
     address_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry 
    ADD CONSTRAINT husbandry_breeder_FK FOREIGN KEY 
    ( 
     id_breeder
    ) 
    REFERENCES breeder 
    ( 
     id_breeder 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry 
    ADD CONSTRAINT husbandry_husbandry_manager_FK FOREIGN KEY 
    ( 
     husbandry_manager_id_husbandry_manager
    ) 
    REFERENCES husbandry_manager 
    ( 
     id_husbandry_manager 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry 
    ADD CONSTRAINT husbandry_husbandry_type_FK FOREIGN KEY 
    ( 
     husbandry_type_id_husbandry_type
    ) 
    REFERENCES husbandry_type 
    ( 
     id_husbandry_type 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry_manager 
    ADD CONSTRAINT husbandry_manager_address_FK FOREIGN KEY 
    ( 
     address_address_ID
    ) 
    REFERENCES address 
    ( 
     address_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE husbandry_manager 
    ADD CONSTRAINT husbandry_manager_husbandry_FK FOREIGN KEY 
    ( 
     husbandry_id_husbandry
    ) 
    REFERENCES husbandry 
    ( 
     id_husbandry 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE nutrition 
    ADD CONSTRAINT nutrition_animal_FK FOREIGN KEY 
    ( 
     animal_id_animal
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE nutrition 
    ADD CONSTRAINT nutrition_feed_FK FOREIGN KEY 
    ( 
     feed_id_feed
    ) 
    REFERENCES feed 
    ( 
     id_feed 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE product 
    ADD CONSTRAINT product_measure_unit_FK FOREIGN KEY 
    ( 
     measure_unit_id_measure_unit
    ) 
    REFERENCES measure_unit 
    ( 
     id_measure_unit 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE productivity 
    ADD CONSTRAINT productivity_animal_FK FOREIGN KEY 
    ( 
     animal_id_animal
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE productivity 
    ADD CONSTRAINT productivity_product_FK FOREIGN KEY 
    ( 
     product_id_product
    ) 
    REFERENCES product 
    ( 
     id_product 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE system_admin 
    ADD CONSTRAINT system_admin_address_FK FOREIGN KEY 
    ( 
     address_address_ID
    ) 
    REFERENCES address 
    ( 
     address_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE vet 
    ADD CONSTRAINT vet_address_FK FOREIGN KEY 
    ( 
     address_address_ID
    ) 
    REFERENCES address 
    ( 
     address_ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE vet_treatment 
    ADD CONSTRAINT vet_treatment_animal_FK FOREIGN KEY 
    ( 
     animal_id_animal
    ) 
    REFERENCES animal 
    ( 
     id_animal 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE vet_treatment 
    ADD CONSTRAINT vet_treatment_vet_FK FOREIGN KEY 
    ( 
     vet_id_vet
    ) 
    REFERENCES vet 
    ( 
     id_vet 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             4
-- ALTER TABLE                             63
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
