 CREATE TABLE "ORDERHEADER" 
   (	"ORDERKEY" VARCHAR2(10), 
	"ORDERDATE" DATE, 
	"DELIVERYDATE" DATE DEFAULT SYSDATE + 3, 
	"CUSTOMERKEY" NUMBER(10,0), 
	"CHANNELKEY" NUMBER(1,0), 
	"PAYMENTMETHODKEY" NUMBER(2,0), 
	"DELIVERYMETHODKEY" NUMBER(1,0), 
	"COUNTRYKEY" NUMBER(2,0), 
	"DELIVERYCOST" NUMBER(5,2), 
	"ORDERSTATUSKEY" NUMBER(1,0)
   ) ;

ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_PK" PRIMARY KEY ("ORDERKEY");

ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_COUNTRY_FK" FOREIGN KEY ("COUNTRYKEY")
	  REFERENCES "COUNTRY" ("COUNTRYKEY") ENABLE;
 
  ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_CUSTOMER_FK" FOREIGN KEY ("CUSTOMERKEY")
	  REFERENCES "CUSTOMER" ("CUSTOMERKEY") ENABLE;
 
  ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_DELIVERYMETHOD_FK" FOREIGN KEY ("DELIVERYMETHODKEY")
	  REFERENCES "DELIVERYMETHOD" ("DELIVERYMETHODKEY") ENABLE;
 
  ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_ORDERCHANNEL_FK" FOREIGN KEY ("CHANNELKEY")
	  REFERENCES "ORDERCHANNEL" ("CHANNELKEY") ENABLE;
 
  ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_PAYMENTMETHOD_FK" FOREIGN KEY ("PAYMENTMETHODKEY")
	  REFERENCES "PAYMENTMETHOD" ("PAYMENTMETHODKEY") ENABLE;
 
  ALTER TABLE "ORDERHEADER" ADD CONSTRAINT "ORDER_STATUS_FK" FOREIGN KEY ("ORDERSTATUSKEY")
	  REFERENCES "ORDERSTATUS" ("ORDERSTATUSKEY") ENABLE;