Insert into PRODUCTCATEGORY (PRODUCTCATEGORYKEY,PRODUCTCATEGORYNAME) values ('1','Bikes');
Insert into PRODUCTCATEGORY (PRODUCTCATEGORYKEY,PRODUCTCATEGORYNAME) values ('2','Components');
Insert into PRODUCTCATEGORY (PRODUCTCATEGORYKEY,PRODUCTCATEGORYNAME) values ('3','Clothing');
Insert into PRODUCTCATEGORY (PRODUCTCATEGORYKEY,PRODUCTCATEGORYNAME) values ('4','Accessories');
