Insert into PAYMENTMETHOD (PAYMENTMETHODKEY,PAYMENTMETHODNAME) values ('5','AstroPay');
Insert into PAYMENTMETHOD (PAYMENTMETHODKEY,PAYMENTMETHODNAME) values ('1','PayPal');
Insert into PAYMENTMETHOD (PAYMENTMETHODKEY,PAYMENTMETHODNAME) values ('2','Bank wire transfer');
Insert into PAYMENTMETHOD (PAYMENTMETHODKEY,PAYMENTMETHODNAME) values ('3','Credit card');
Insert into PAYMENTMETHOD (PAYMENTMETHODKEY,PAYMENTMETHODNAME) values ('4','Debit card');
