Insert into SALESTERRITORY (SALESTERRITORYKEY,SALESTERRITORYNAME) values ('3','Australia');
Insert into SALESTERRITORY (SALESTERRITORYKEY,SALESTERRITORYNAME) values ('2','Europe');
Insert into SALESTERRITORY (SALESTERRITORYKEY,SALESTERRITORYNAME) values ('1','North America');
