Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('337','Clarkston','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('338','Columbus','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('339','Decatur','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('340','La Grange','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('341','Marietta','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('342','Mcdonough','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('343','Savannah','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('344','Suwanee','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('345','Idaho Falls','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('346','Lewiston','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('347','Sandpoint','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('348','Carol Stream','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('349','Chicago','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('350','Elgin','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('351','Joliet','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('352','Moline','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('353','Norridge','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('354','Peoria','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('355','Tuscola','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('356','West Chicago','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('357','Wood Dale','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('358','Daleville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('359','Fort Wayne','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('360','Indianapolis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('361','Logansport','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('362','Michigan City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('363','New Castle','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('364','South Bend','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('365','Campbellsville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('366','Newport','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('367','Saint Matthews','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('368','Somerset','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('369','Braintree','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('370','Norwood','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('371','Randolph','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('372','Saugus','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('373','Wrentham','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('374','Baltimore','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('375','Kittery','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('376','Detroit','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('377','Holland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('378','Howell','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('379','Madison Heights','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('380','Midland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('381','Monroe','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('382','Novi','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('383','Pontiac','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('384','Port Huron','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('385','Redford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('386','Saginaw','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('387','Southfield','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('388','Southgate','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('389','Westland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('390','Zeeland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('391','Branch','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('392','Duluth','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('393','Edina','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('394','Medford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('395','Minneapolis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('396','Woodbury','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('397','Branson','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('398','Ferguson','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('399','Jefferson City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('400','Kansas City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('401','Odessa','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('402','Saint Ann','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('403','Saint Louis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('404','Biloxi','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('405','Gulfport','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('406','Tupelo','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('407','Billings','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('408','Great Falls','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('409','Missoula','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('410','Charlotte','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('411','Greensboro','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('412','Kannapolis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('413','Raleigh','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('414','Rocky Mount','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('415','Smithfield','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('416','Winston-Salem','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('417','Hooksett','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('418','Nashua','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('419','Plaistow','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('420','Tilton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('421','Las Cruces','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('422','Rio Rancho','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('423','Santa Fe','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('424','Fernley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('425','Las Vegas','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('426','North Las Vegas','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('427','Reno','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('428','Sparks','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('429','Central Valley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('430','Cheektowaga','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('431','Clay','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('432','De Witt','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('433','Endicott','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('434','Ithaca','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('435','Lake George','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('436','Melville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('437','New Hartford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('438','New York','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('439','Valley Stream','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('440','Cincinnati','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('441','Euclid','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('442','Heath','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('443','Mansfield','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('444','Mentor','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('445','North Randall','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('446','Oberlin','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('447','Springdale','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('448','Albany','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('449','Beaverton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('450','Clackamas','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('451','Corvallis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('452','Hillsboro','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('453','Klamath Falls','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('454','Lake Oswego','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('455','Lebanon','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('456','Milwaukie','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('457','Oregon City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('458','Portland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('459','Salem','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('460','Springfield','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('461','Tigard','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('462','Troutdale','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('463','W. Linn','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('464','Woodburn','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('465','Warwick','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('466','West Kingston','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('467','Woonsocket','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('468','Bluffton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('469','Gaffney','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('470','Myrtle Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('471','Denby','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('472','North Sioux City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('473','Crossville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('474','Hixson','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('475','Kingsport','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('476','La Vergne','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('477','Maryville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('478','Memphis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('479','Millington','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('480','Nashville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('481','Pigeon Forge','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('482','Arlington','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('483','Austin','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('484','Baytown','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('485','Carrollton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('486','Cedar Park','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('487','College Station','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('488','Corpus Christi','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('489','Dallas','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('490','Fort Worth','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('491','Garland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('492','Houston','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('493','Humble','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('494','Irving','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('495','Killeen','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('496','La Marque','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('497','Laredo','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('498','Mesquite','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('499','Plano','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('500','Round Rock','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('501','San Antonio','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('502','Stafford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('503','Sugar Land','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('504','Bountiful','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('505','Cedar City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('506','Ogden','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('507','Park City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('508','Riverton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('509','Salt Lake City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('510','Sandy','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('511','Tooele','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('512','Chantilly','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('513','Falls Church','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('514','Leesburg','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('515','Newport News','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('516','Virginia Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('517','Ballard','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('518','Bellevue','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('519','Bellingham','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('520','Bothell','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('521','Bremerton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('522','Burien','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('523','Chehalis','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('524','Edmonds','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('525','Ellensburg','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('526','Everett','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('527','Federal Way','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('528','Issaquah','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('529','Kelso','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('530','Kenmore','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('531','Kennewick','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('532','Kent','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('533','Kirkland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('534','Lacey','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('535','Longview','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('536','Lynnwood','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('537','Marysville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('538','Newport Hills','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('539','North Bend','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('540','Olympia','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('541','Port Orchard','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('542','Puyallup','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('543','Redmond','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('544','Renton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('545','Sammamish','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('546','Seattle','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('547','Sedro Woolley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('548','Sequim','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('549','Shelton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('550','Spokane','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('551','Tacoma','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('552','Union Gap','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('553','Walla Walla','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('554','Washougal','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('555','Wenatchee','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('556','Woodinville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('557','Yakima','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('558','Johnson Creek','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('559','Milwaukee','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('560','Mosinee','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('561','Racine','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('562','Casper','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('563','Cheyenne','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('564','Rock Springs','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('565','Warsaw','8');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('566','Cracow','8');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('567','Gdansk','8');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('568','Poznan','8');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('569','Rome','7');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('570','Milan','7');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('571','Naples','7');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('572','Venice','7');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('573','Amsterdam','9');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('574','Antwerp','9');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('575','Maastricht','9');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('576','Haga','9');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('577','Rotterdam','9');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('578','Madrid','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('579','Alicante','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('580','Murcia','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('581','Sevilla','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('582','Valencia','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('583','Barcelona','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('584','Cordoba','10');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('1','Alexandria','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('2','Coffs Harbour','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('3','Darlinghurst','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('4','Goulburn','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('5','Lane Cove','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('6','Lavender Bay','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('7','Malabar','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('8','Matraville','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('9','Milsons Point','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('10','Newcastle','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('11','North Ryde','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('12','North Sydney','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('13','Port Macquarie','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('14','Rhodes','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('15','Silverwater','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('16','Springwood','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('17','St. Leonards','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('18','Sydney','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('19','Wollongong','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('20','Brisbane','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('21','Caloundra','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('22','East Brisbane','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('23','Gold Coast','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('24','Hawthorne','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('25','Hervey Bay','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('26','Rockhampton','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('27','Townsville','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('28','Cloverdale','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('29','Findon','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('30','Perth','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('31','Hobart','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('32','Bendigo','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('33','Cranbourne','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('34','Geelong','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('35','Melbourne','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('36','Melton','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('37','Seaford','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('38','South Melbourne','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('39','Sunbury','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('40','Warrnambool','5');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('41','Calgary','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('42','Edmonton','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('43','Burnaby','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('44','Cliffside','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('45','Haney','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('46','Langford','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('47','Langley','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('48','Metchosin','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('49','N. Vancouver','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('50','Newton','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('51','Oak Bay','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('52','Port Hammond','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('53','Richmond','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('54','Royal Oak','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('55','Shawnee','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('56','Sooke','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('57','Surrey','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('58','Vancouver','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('59','Victoria','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('60','Westminster','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('61','Winnipeg','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('62','Saint John','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('63','Aurora','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('64','Barrie','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('65','Brampton','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('66','Chalk Riber','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('67','Etobicoke','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('68','Kanata','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('69','Kingston','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('70','Markham','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('71','Mississauga','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('72','Nepean','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('73','North York','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('74','Ottawa','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('75','Richmond Hill','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('76','Scarborough','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('77','Toronto','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('78','Waterloo','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('79','Weston','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('80','Brossard','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('81','Dorval','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('82','Hull','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('83','Montreal','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('84','Outremont','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('85','Pnot-Rouge','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('86','Quebec','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('87','Sainte-Foy','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('88','Sillery','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('89','Ville De''anjou','4');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('90','Berlin','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('91','Eilenburg','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('92','Augsburg','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('93','Erlangen','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('94','Frankfurt','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('95','Grevenbroich','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('96','Hof','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('97','Ingolstadt','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('98','Bad Soden','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('99','Darmstadt','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('100','Dresden','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('101','Duesseldorf','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('102','Hamburg','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('103','Kassel','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('104','M?nchen','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('105','Salzgitter','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('106','Ascheim','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('107','Bonn','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('108','Essen','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('109','Frankfurt am Main','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('110','Muehlheim','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('111','M?hlheim','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('112','Paderborn','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('113','Bottrop','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('114','Braunschweig','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('115','Hannover','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('116','Leipzig','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('117','Solingen','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('118','Werne','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('119','Kiel','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('120','M?nster','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('121','Neunkirchen','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('122','Offenbach','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('123','Poing','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('124','Saarbr?cken','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('125','Saarlouis','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('126','Stuttgart','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('127','Sulzbach Taunus','2');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('128','Saint Ouen','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('129','Colomiers','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('130','Aujan Mournede','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('131','Orleans','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('132','Metz','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('133','Croix','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('134','Dunkerque','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('135','Lille','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('136','Roncq','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('137','Roubaix','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('138','Villeneuve-d''Ascq','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('139','Boulogne-sur-Mer','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('140','Paris','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('141','Lieusaint','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('142','Roissy en Brie','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('143','Chatou','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('144','Saint Germain en Laye','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('145','Versailles','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('146','Les Ulis','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('147','Morangis','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('148','Verrieres Le Buisson','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('149','Boulogne-Billancourt','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('150','Colombes','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('151','Courbevoie','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('152','Paris La Defense','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('153','S?vres','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('154','Suresnes','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('155','Bobigny','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('156','Drancy','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('157','Pantin','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('158','Saint-Denis','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('159','Tremblay-en-France','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('160','Orly','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('161','Cergy','6');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('162','Abingdon','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('163','Basingstoke Hants','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('164','Berks','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('165','Berkshire','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('166','Billericay','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('167','Birmingham','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('168','Bracknell','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('169','Bury','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('170','Cambridge','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('171','Cheltenham','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('172','Esher-Molesey','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('173','Gateshead','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('174','Gloucestershire','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('175','High Wycombe','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('176','Kirkby','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('177','Lancaster','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('178','Leeds','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('179','London','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('180','Maidenhead','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('181','Milton Keynes','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('182','Newcastle upon Tyne','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('183','Oxford','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('184','Oxon','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('185','Peterborough','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('186','Reading','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('187','Runcorn','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('188','Liverpool','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('189','Stoke-on-Trent','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('190','W. York','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('191','Warrington','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('192','Watford','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('193','West Sussex','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('194','Wokingham','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('195','Woolston','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('196','York','3');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('197','Birmingham','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('198','Florence','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('199','Huntsville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('200','Mobile','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('201','Montgomery','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('202','Chandler','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('203','Gilbert','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('204','Mesa','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('205','Phoenix','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('206','Scottsdale','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('207','Surprise','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('208','Tucson','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('209','Alhambra','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('210','Alpine','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('211','Auburn','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('212','Baldwin Park','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('213','Barstow','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('214','Bell Gardens','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('215','Bellflower','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('216','Berkeley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('217','Beverly Hills','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('218','Burbank','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('219','Burlingame','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('220','Camarillo','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('221','Canoga Park','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('222','Carson','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('223','Cerritos','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('224','Chula Vista','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('225','Citrus Heights','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('226','City Of Commerce','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('227','Colma','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('228','Concord','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('229','Coronado','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('230','Culver City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('231','Daly City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('232','Downey','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('233','El Cajon','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('234','El Segundo','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('235','Elk Grove','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('236','Escondido','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('237','Eureka','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('238','Fontana','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('239','Fremont','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('240','Fullerton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('241','Gilroy','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('242','Glendale','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('243','Grossmont','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('244','Hanford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('245','Hayward','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('246','Imperial Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('247','Irvine','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('248','La Jolla','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('249','La Mesa','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('250','Lake Elsinore','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('251','Lakewood','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('252','Lemon Grove','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('253','Lincoln Acres','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('254','Long Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('255','Los Angeles','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('256','Mill Valley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('257','Milpitas','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('258','Modesto','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('259','Monrovia','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('260','National City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('261','Newark','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('262','Newport Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('263','Norwalk','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('264','Novato','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('265','Oakland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('266','Ontario','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('267','Orange','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('268','Oxnard','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('269','Palo Alto','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('270','Pleasanton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('271','Redlands','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('272','Redwood City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('273','Sacramento','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('274','San Bruno','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('275','San Carlos','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('276','San Diego','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('277','San Francisco','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('278','San Gabriel','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('279','San Jose','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('280','San Mateo','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('281','San Ramon','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('282','San Ysidro','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('283','Sand City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('284','Santa Ana','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('285','Santa Cruz','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('286','Santa Monica','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('287','Sherman Oaks','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('288','Simi Valley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('289','Spring Valley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('290','Stockton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('291','Torrance','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('292','Trabuco Canyon','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('293','Union City','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('294','Upland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('295','Vacaville','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('296','Van Nuys','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('297','Visalia','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('298','Vista','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('299','Walnut Creek','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('300','West Covina','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('301','Whittier','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('302','Woodland Hills','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('303','Denver','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('304','Englewood','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('305','Greeley','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('306','Longmont','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('307','Loveland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('308','Parker','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('309','Westminster','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('310','East Haven','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('311','Farmington','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('312','Hamden','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('313','Milford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('314','New Haven','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('315','Stamford','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('316','Waterbury','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('317','Westport','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('318','Altamonte Springs','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('319','Bradenton','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('320','Clearwater','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('321','Destin','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('322','Hollywood','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('323','Kendall','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('324','Lakeland','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('325','Merritt Island','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('326','Miami','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('327','North Miami Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('328','Orlando','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('329','Sarasota','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('330','Sunrise','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('331','Tampa','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('332','Vero Beach','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('333','Atlanta','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('334','Augusta','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('335','Austell','1');
Insert into CITY (CITYKEY,CITYNAME,COUNTRYKEY) values ('336','Byron','1');
