Insert into DELIVERYMETHOD (DELIVERYMETHODKEY,DELIVERYMETHODNAME) values ('1','UPC');
Insert into DELIVERYMETHOD (DELIVERYMETHODKEY,DELIVERYMETHODNAME) values ('2','TNT');
Insert into DELIVERYMETHOD (DELIVERYMETHODKEY,DELIVERYMETHODNAME) values ('3','DHL');
Insert into DELIVERYMETHOD (DELIVERYMETHODKEY,DELIVERYMETHODNAME) values ('4','DPD Courier');
Insert into DELIVERYMETHOD (DELIVERYMETHODKEY,DELIVERYMETHODNAME) values ('5','Parcel GLS');
