# -*- coding: utf-8 -*-
"""pytorch_workflows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9V-RruhwcvDdBBEWnQzHpLAogEYbHvG
"""

import torch
from torch import nn
import matplotlib.pyplot as plt

torch.__version__

## **Regresja Liniowa**
weight = 0.7
bias = 0.3

#create
start = 0
end = 1
step = 0.02
X = torch.arange(start,end,step).unsqueeze(dim=1)
y = weight * X + bias

X[:10], y[:10], len(X), len(y)

## Spliting data nto training and test sets
train_split = int(0.8 * len(X))
x_train, y_train = X[:train_split], y[:train_split]
x_test, y_test = X[train_split:], y[train_split:]
len(x_train), len(x_test), len(y_train), len(y_test)

def plot_predictions(train_data = x_train,
                     train_labels=y_train,
                     test_data=x_test, # Corrected: should be x_test
                     test_labels=y_test,
                     predictions= None):
  plt.figure(figsize=(10,7))

  #traning = blue
  plt.scatter(train_data, train_labels, c="b", s=4, label="Training Data")

  #test = green
  plt.scatter(test_data, test_labels, c="g", s=4, label="Testing Data")

  if predictions is not None:
    plt.scatter(test_data, predictions, c="r", s=4, label="Predictions")

  plt.legend(prop={"size":14})

plot_predictions()

## Building a linear regression model
## Gradient descent
## back propagation

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1,
                                                requires_grad=True,
                                                dtype= torch.float))
        self.bias = nn.Parameter(torch.randn(1,
                                            requires_grad=True,
                                            dtype=torch.float))
    #Forward method to define computation
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.weights * x + self.bias;

torch.manual_seed(42)
model = LinearRegressionModel()
list(model.parameters())
model.state_dict()

## predicting with torch.inference_mode()

with torch.inference_mode():
  y_preds = model(x_test);

plot_predictions(predictions=y_preds)

##set up loss function
loss_fn = nn.L1Loss()

#set up optimizer - stochastic gradient descent
optimizer = torch.optim.SGD(params = model.parameters(),
                           lr=0.01)

#building a training (and testing) loop
torch.manual_seed(42)
epochs = 200

epoch_count=[]
loss_values=[]
test_loss_values=[]

# 0. loop through data
for epoch in range(epochs):
    model.train() #set model to training mode - requires gradient

    # 1. forwards pass
    y_pred = model(x_train)

    # 2. Calculate the loss
    loss = loss_fn(y_pred, y_train)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backwards (back propagation)
    loss.backward()

    # 5. Optimizer step (gradient descent)
    optimizer.step()

    if(epoch % 10 == 0):
        # Zwiększono precyzję wyświetlania loss i parametrów
        print(f"Epoch: {epoch}, Loss: {loss.item():.10f}")

    #TESTING
    model.eval() #turns off some settings not needed for testing
    with torch.inference_mode():
        test_pred = model(x_test) #forward pass
        test_loss = loss_fn(test_pred, y_test) #calculating loss
        if(epoch % 10 == 0):
            epoch_count.append(epoch)
            loss_values.append(loss.item())
            test_loss_values.append(test_loss.item())


            print(f"Epoch: {epoch}, Loss: {loss.item():.10f}, Test Loss: {test_loss.item():.10f}")
            # Wyświetl pełny state_dict z większą precyzją dla poszczególnych parametrów
            print(f"Model state: weights={model.state_dict()['weights'].item():.10f}, bias={model.state_dict()['bias'].item():.10f}")


print(f"Final Model state: weights={model.state_dict()['weights'].item():.10f}, bias={model.state_dict()['bias'].item():.10f}")

plt.plot(epoch_count, loss_values, label="Train loss")
plt.plot(epoch_count, test_loss_values, label="Test loss")
plt.title("Training and testing loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.legend()

model.state_dict()

weight, bias

with torch.inference_mode():
    y_preds_new = model(x_test)
plot_predictions(predictions=y_preds_new)

#save the model
from pathlib import Path

#create models directory
MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True, exist_ok=True)

MODEL_NAME = "01_pytorch_workflow.pth"
MODEL_SAVE_PATH = MODEL_PATH / MODEL_NAME

print(f"Saving model to {MODEL_SAVE_PATH}")
torch.save(obj=model.state_dict(), f=MODEL_SAVE_PATH)

##loading a model (creating a new isntance and importing saved state_dict())
loaded_model = LinearRegressionModel()
loaded_model.load_state_dict(torch.load(f=MODEL_SAVE_PATH))
loaded_model

"""# Next model using linear layers"""

class LinearRegressionModelV2(nn.Module):
    def __init__(self):
        super().__init__()

        self.linear_layer = nn.Linear(in_features=1, out_features=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.linear_layer(x)

torch.manual_seed(42)
model_1 = LinearRegressionModelV2()
model_1, model_1.state_dict()

loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params= model_1.parameters(),
                            lr=0.01)

epochs = 200

for epoch in range(epochs):
    model_1.train()

    y_pred = model_1(x_train)

    loss = loss_fn(y_pred, y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    #testing
    model_1.eval()
    with torch.inference_mode():
        test_pred = model_1(x_test)
        test_loss = loss_fn(test_pred, y_test)

    if (epoch%10==0):
        print(f"Epoch: {epoch}, Loss: {loss}, Test loss: {test_loss}")
print(f"Model params: {model_1.state_dict()}")

